### ISSUE TITLE
PTZOptics camera & "PTZ Controls" Plugin

### ISSUE THREAD

**Issue by danielbates7** [PTZOptics/OBSPlugin#8]
Hi I have a PT12X-NDI-XX I am trying to control via the "PTZ Controls" Plug-In. I have it added as a NDI source and see video. But when adding it to the PTZ controls plugin it won't work. any ideas?

**Comment by xLionTamer** [comment]
PTZ Controls is a different plugin:
https://github.com/glikely/obs-ptz
